name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main  # Setiap ada push ke main, otomatis deploy

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js versi terbaru
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build VitePress site
      - name: Build VitePress site
        run: npm run docs:build

      # 5. Deploy ke branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
